// Generated by gencpp from file otp/pos.msg
// DO NOT EDIT!


#ifndef OTP_MESSAGE_POS_H
#define OTP_MESSAGE_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace otp
{
template <class ContainerAllocator>
struct pos_
{
  typedef pos_<ContainerAllocator> Type;

  pos_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , stamp(0.0)  {
    }
  pos_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , stamp(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _stamp_type;
  _stamp_type stamp;




  typedef boost::shared_ptr< ::otp::pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::otp::pos_<ContainerAllocator> const> ConstPtr;

}; // struct pos_

typedef ::otp::pos_<std::allocator<void> > pos;

typedef boost::shared_ptr< ::otp::pos > posPtr;
typedef boost::shared_ptr< ::otp::pos const> posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::otp::pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::otp::pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace otp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'otp': ['/home/heramb/HoldMyCup/src/otp/msg', '/home/heramb/HoldMyCup/src/otp/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::otp::pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::otp::pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::otp::pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::otp::pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::otp::pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::otp::pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::otp::pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8db2f7ec4670b9947cee9d5eba2c34";
  }

  static const char* value(const ::otp::pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8db2f7ec4670b9ULL;
  static const uint64_t static_value2 = 0x947cee9d5eba2c34ULL;
};

template<class ContainerAllocator>
struct DataType< ::otp::pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "otp/pos";
  }

  static const char* value(const ::otp::pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::otp::pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 stamp\n\
\n\
";
  }

  static const char* value(const ::otp::pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::otp::pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::otp::pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::otp::pos_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "stamp: ";
    Printer<double>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OTP_MESSAGE_POS_H
