// Generated by gencpp from file kinect_data/joint.msg
// DO NOT EDIT!


#ifndef KINECT_DATA_MESSAGE_JOINT_H
#define KINECT_DATA_MESSAGE_JOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinect_data
{
template <class ContainerAllocator>
struct joint_
{
  typedef joint_<ContainerAllocator> Type;

  joint_()
    : joint_name()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , stamp(0.0)  {
    }
  joint_(const ContainerAllocator& _alloc)
    : joint_name(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , stamp(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joint_name_type;
  _joint_name_type joint_name;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _stamp_type;
  _stamp_type stamp;




  typedef boost::shared_ptr< ::kinect_data::joint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_data::joint_<ContainerAllocator> const> ConstPtr;

}; // struct joint_

typedef ::kinect_data::joint_<std::allocator<void> > joint;

typedef boost::shared_ptr< ::kinect_data::joint > jointPtr;
typedef boost::shared_ptr< ::kinect_data::joint const> jointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinect_data::joint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinect_data::joint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinect_data

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'kinect_data': ['/home/heramb/HoldMyCup/src/kinect_data/msg', '/home/heramb/HoldMyCup/src/kinect_data/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinect_data::joint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinect_data::joint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_data::joint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_data::joint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_data::joint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_data::joint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinect_data::joint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3839ec54a06735177ec15f683b659314";
  }

  static const char* value(const ::kinect_data::joint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3839ec54a0673517ULL;
  static const uint64_t static_value2 = 0x7ec15f683b659314ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_data::joint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect_data/joint";
  }

  static const char* value(const ::kinect_data::joint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinect_data::joint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string joint_name\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 stamp\n\
\n\
";
  }

  static const char* value(const ::kinect_data::joint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinect_data::joint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_data::joint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinect_data::joint_<ContainerAllocator>& v)
  {
    s << indent << "joint_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_name);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "stamp: ";
    Printer<double>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINECT_DATA_MESSAGE_JOINT_H
