// Generated by gencpp from file kinect_data/skeleton.msg
// DO NOT EDIT!


#ifndef KINECT_DATA_MESSAGE_SKELETON_H
#define KINECT_DATA_MESSAGE_SKELETON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kinect_data/joint.h>

namespace kinect_data
{
template <class ContainerAllocator>
struct skeleton_
{
  typedef skeleton_<ContainerAllocator> Type;

  skeleton_()
    : joints()  {
    }
  skeleton_(const ContainerAllocator& _alloc)
    : joints()  {
  (void)_alloc;
      joints.assign( ::kinect_data::joint_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::kinect_data::joint_<ContainerAllocator> , 4>  _joints_type;
  _joints_type joints;




  typedef boost::shared_ptr< ::kinect_data::skeleton_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_data::skeleton_<ContainerAllocator> const> ConstPtr;

}; // struct skeleton_

typedef ::kinect_data::skeleton_<std::allocator<void> > skeleton;

typedef boost::shared_ptr< ::kinect_data::skeleton > skeletonPtr;
typedef boost::shared_ptr< ::kinect_data::skeleton const> skeletonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinect_data::skeleton_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinect_data::skeleton_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinect_data

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'kinect_data': ['/home/heramb/HoldMyCup/src/kinect_data/msg', '/home/heramb/HoldMyCup/src/kinect_data/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinect_data::skeleton_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinect_data::skeleton_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_data::skeleton_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_data::skeleton_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_data::skeleton_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_data::skeleton_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinect_data::skeleton_<ContainerAllocator> >
{
  static const char* value()
  {
    return "870ea4c4d6154329d5d481442838f2f5";
  }

  static const char* value(const ::kinect_data::skeleton_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x870ea4c4d6154329ULL;
  static const uint64_t static_value2 = 0xd5d481442838f2f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_data::skeleton_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect_data/skeleton";
  }

  static const char* value(const ::kinect_data::skeleton_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinect_data::skeleton_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect_data/joint[4] joints \n\
\n\
================================================================================\n\
MSG: kinect_data/joint\n\
string joint_name\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 stamp\n\
\n\
";
  }

  static const char* value(const ::kinect_data::skeleton_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinect_data::skeleton_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct skeleton_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_data::skeleton_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinect_data::skeleton_<ContainerAllocator>& v)
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kinect_data::joint_<ContainerAllocator> >::stream(s, indent + "    ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINECT_DATA_MESSAGE_SKELETON_H
